name: Create and Notify DNS Record

on:
  push:
    branches:
      - main  # Replace with your branch name
  workflow_dispatch:

jobs:
  create-dns-record:
    runs-on: ubuntu-latest
    steps:
    - name: Show Available Records
      run: |
        CF_API_TOKEN="HsoabgfSbNQVeHpg30hI14GOo8mZLixzk_7HhJY8"
        ZONE_ID="38b42bfdb42dbe301b6b1a27b86ac939"

        API_URL="https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records"

        curl -s -H "Authorization: Bearer $CF_API_TOKEN" "$API_URL" | jq .
  
    - name: Create/Update CloudFlare DNS Records
  # You may pin to the exact commit or the version.
  # uses: everpcpc/cloudflare-dns-action@0ad4c3673f7d2cba45350befaab2f50f574c963e
      uses: everpcpc/cloudflare-dns-action@v1
      with:
        type: CNAME
        name: Tayyub-butt.karazo.com
        content: isaadiqbal.github.io/dns-check/
        ttl: 36000
        apiKey: HsoabgfSbNQVeHpg30hI14GOo8mZLixzk_7HhJY8
        zone: 38b42bfdb42dbe301b6b1a27b86ac939
   
